#!/usr/bin/python

"""This is the main executable for DeviceManager. GTK+/Glade code is based
on simplepy from Shannon -jj Behrens <jjinux@yahoo.com>"""

import pygtk
pygtk.require('2.0')
import gtk
import gnome

import Const
import LibGladeApplication
from DeviceManager import DeviceManager

gnome.program_init(Const.NAME, Const.VERSION)
DeviceManager()
gtk.mainloop()
