#!/bin/sh
#
# Copyright (C) 2007 Bastien Nocera <bnocera@redhat.com>
# Copyright (C) 2007 David Zeuthen <davidz@redhat.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

if [ "$HAL_PROP_KILLSWITCH_TYPE" = "bluetooth" ]; then
    if [ "$HAL_PROP_KILLSWITCH_ACCESS_METHOD" = "sonypic" ]; then
	hal-system-sonypic setbluetooth $value
	if [ $? -ne 0 ]; then
	    echo "org.freedesktop.Hal.Device.KillSwitch.NotSupported" >&2
	    exit 1
	fi
	exit 0
    elif [ "$HAL_PROP_KILLSWITCH_ACCESS_METHOD" = "dell" -a -x /usr/bin/dellWirelessCtl ]; then

	# As a side effect we disable the physical kill switch

	# TODO: write our own binary that links with libsmbios?
	if [ "$value" = "true" ]; then
	    /usr/bin/dellWirelessCtl --sw_bt 0 --bt 1
	    ret=$?
	else
	    /usr/bin/dellWirelessCtl --sw_bt 0 --bt 0
	    ret=$?
	fi
	if [ "$ret" != "0" ]; then
	    echo "org.freedesktop.Hal.Device.KillSwitch.NotSupported" >&2
	    echo "dellWirelessCtl returned $ret" >&2
	fi
    else
	echo "org.freedesktop.Hal.Device.KillSwitch.NotSupported" >&2
	echo "Access type not supported" >&2
	exit 1
    fi
elif [ "$HAL_PROP_KILLSWITCH_TYPE" = "wlan" ]; then
    if [ "$HAL_PROP_KILLSWITCH_ACCESS_METHOD" = "dell" -a -x /usr/bin/dellWirelessCtl ]; then

	# As a side effect we disable the physical kill switch

	# TODO: write our own binary that links with libsmbios?
	if [ "$value" = "true" ]; then
	    /usr/bin/dellWirelessCtl --sw_wlan 0 --wlan 1
	    ret=$?
	else
	    /usr/bin/dellWirelessCtl --sw_wlan 0 --wlan 0
	    ret=$?
	fi
	if [ "$ret" != "0" ]; then
	    echo "org.freedesktop.Hal.Device.KillSwitch.NotSupported" >&2
	    echo "dellWirelessCtl returned $ret" >&2
	fi
    else
	echo "org.freedesktop.Hal.Device.KillSwitch.NotSupported" >&2
	echo "Access type not supported" >&2
	exit 1
    fi
else
    echo "org.freedesktop.Hal.Device.KillSwitch.NotSupported" >&2
    echo "Killswitch type not supported" >&2
    exit 1
fi

