#!/bin/sh
#
# Copyright (C) 2006 Richard Hughes <richard@hughsie.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# Check we are the root user
if [ "$HAL_METHOD_INVOKED_BY_UID" != "0" ] ; then
    echo "org.freedesktop.Hal.Device.Video.PermissionDeniedByUID" >&2
    echo "hal-system-video-resume refused uid $HAL_METHOD_INVOKED_BY_UID" >&2
    exit 1
fi

# We might need to do one or many of these quirks
if [ "$HAL_PROP_VIDEO_ADAPTER_PM_VBE_POST" == "true" ]; then
	/usr/sbin/vbetool post
fi
if [ "$HAL_PROP_VIDEO_ADAPTER_PM_VBESTATE_RESTORE" == "true" ]; then
	/usr/sbin/vbetool vbestate restore < /var/run/vbestate
fi
if [ "$HAL_PROP_VIDEO_ADAPTER_PM_VBEMODE_RESTORE" == "true" ]; then
	/usr/sbin/vbetool vbemode set `cat /var/run/vbemode`
fi
if [ "$HAL_PROP_VIDEO_ADAPTER_PM_DPMS_ON" == "true" ]; then
	/usr/sbin/vbetool dpms on > /dev/null 2>&1
fi

exit 0
