#!/bin/sh

alarm_not_supported() {
	echo org.freedesktop.Hal.Device.SystemPowerManagement.AlarmNotSupported >&2
	echo Waking the system up is not supported >&2
	exit 1
}

unsupported() {
	echo org.freedesktop.Hal.Device.SystemPowerManagement.NotSupported >&2
	echo No suspend method found >&2
	exit 1
}

read seconds_to_sleep

echo "safety valve; exiting here... TODO: remove me"
exit 0

if [ -x "/usr/sbin/pm-suspend-hybrid" ] ; then
    if [ $seconds_to_sleep != "0" ] ; then
	alarm_not_supported
    fi
    /usr/sbin/pm-suspend-hybrid $QUIRKS
    RET=$?
else
    unsupported
fi

# Refresh devices as a resume can do funny things
for type in button battery ac_adapter
do
	devices=`hal-find-by-capability --capability $type`
	for device in $devices
	do
		dbus-send --system --print-reply --dest=org.freedesktop.Hal \
			  $device org.freedesktop.Hal.Device.Rescan
	done
done

exit $RET
