#!/bin/sh
#
# Copyright (C) 2006 Richard Hughes <richard@hughsie.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# Check we are the root user
if [ "$HAL_METHOD_INVOKED_BY_UID" != "0" ] ; then
    echo "org.freedesktop.Hal.Device.Video.PermissionDeniedByUID" >&2
    echo "hal-system-video-resume refused uid $HAL_METHOD_INVOKED_BY_UID" >&2
    exit 1
fi

checkvbetool() {
    if ! [ -x "/usr/sbin/vbetool" ]; then
        echo org.freedesktop.Hal.Device.Video.NotSupported >&2
        echo vbetool not found or not executable >&2
        exit 1
    fi
}

# We might need to do one or many of these quirks
if [ "$HAL_PROP_VIDEO_ADAPTER_PM_VBE_POST" == "true" ]; then
	checkvbetool
	/usr/sbin/vbetool post
fi
if [ "$HAL_PROP_VIDEO_ADAPTER_PM_VBESTATE_RESTORE" == "true" ]; then
	checkvbetool
	if [ -f /var/run/vbestate ]; then
		/usr/sbin/vbetool vbestate restore < /var/run/vbestate
	else
		echo org.freedesktop.Hal.Device.Video.UnableToRetore>&2
	        echo /var/run/vbestate is missing, can not restore >&2
        	exit 1
	fi
fi
if [ "$HAL_PROP_VIDEO_ADAPTER_PM_VBEMODE_RESTORE" == "true" ]; then
	checkvbetool
	if [ -f /var/run/vbemode ]; then
		/usr/sbin/vbetool vbemode set `cat /var/run/vbemode`
	else
		echo org.freedesktop.Hal.Device.Video.UnableToRetore>&2
	        echo /var/run/vbemode is missing, can not restore >&2
        	exit 1
	fi
fi
if [ "$HAL_PROP_VIDEO_ADAPTER_PM_DPMS_ON" == "true" ]; then
	checkvbetool
	/usr/sbin/vbetool dpms on > /dev/null 2>&1
fi

exit 0
