#!/bin/sh
#
# Copyright (C) 2007 Bastien Nocera <bnocera@redhat.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

if [ "$HAL_PROP_KILLSWITCH_ACCESS_METHOD" = "sonypic" ]; then
	hal-system-sonypic setbluetooth $value
	if [ $? -ne 0 ]; then
		echo "org.freedesktop.Hal.Device.BluetoothButton.NotSupported" >&2
		exit 1
	fi
	exit 0
else
	echo "org.freedesktop.Hal.Device.BluetoothButton.NotSupported" >&2
	echo "Access type not supported" >&2
	exit 1
fi

