#!/bin/sh
#
# Copyright (C) 2005 Richard Hughes <richard@hughsie.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# Check for environment variables
if [ -z "$HAL_PROP_LAPTOP_PANEL_ACCESS_METHOD" ]; then
	echo "Missing or empty environment variable(s)." >&2
	echo "This script should be started by hald." >&2
	exit 1
fi

if [ -n "$HALD_UNAME_S" -a -x ./$0-$HALD_UNAME_S ]; then
    exec ./$0-$HALD_UNAME_S $@
else
    echo "No back-end for your operating system" >&2
    exit 1
fi
