#!/bin/sh

POWERSAVED_SUSPEND2DISK="dbus-send --system --dest=com.novell.powersave \
                         --print-reply /com/novell/powersave \
                         com.novell.powersave.action.SuspendToDisk"

unsupported() {
	echo org.freedesktop.Hal.Device.SystemPowerManagement.NotSupported >&2
	echo No hibernate script found >&2
	exit 1
}

POLICY=power-hibernate
if [ "$HAL_METHOD_INVOKED_BY_UID" != "0" ] ; then
    hal-policy-is-privileged --policy $POLICY --uid $HAL_METHOD_INVOKED_BY_UID
    IS_PRIVILEGED=$?
    if [ "$IS_PRIVILEGED" != "0" ] ; then
	echo org.freedesktop.Hal.Device.PermissionDeniedByPolicy >&2
	echo uid $HAL_METHOD_INVOKED_BY_UID refused by policy "$POLICY" >&2
	exit 1
    fi
fi

#SuSE and ALTLinux only support powersave
if [ -f /etc/altlinux-release ] || [ -f "/etc/SuSE-release" ] ; then
	if [ -x /usr/bin/powersave ] ; then
	        $POWERSAVED_SUSPEND2DISK
		RET=$?
	else
		unsupported
	fi

#RedHat/Fedora only support pm-utils
elif [ -f /etc/redhat-release ] || [ -f /etc/fedora-release ] ; then
	if [ -x /usr/sbin/pm-hibernate ] ; then
		/usr/sbin/pm-hibernate
		RET=$?
	else
		unsupported
	fi

#Other distros just need to have *any* tools installed
else
	if [ -x "/usr/bin/powersave" ] ; then
	        $POWERSAVED_SUSPEND2DISK
		RET=$?
	elif [ -x "/usr/sbin/pmi" ] ; then
		/usr/sbin/pmi action hibernate force
		RET=$?
	elif [ -x "/usr/sbin/pm-hibernate" ] ; then
		/usr/sbin/pm-hibernate
		RET=$?
	elif [ -x "/usr/sbin/hibernate" ] ; then
		# Suspend2 tools installed
		/usr/sbin/hibernate --force
		RET=$?
	elif [ -w "/sys/power/state" ] ; then
		# Use the raw kernel sysfs interface
		echo "disk" > /sys/power/state
		RET=$?
	else
		unsupported
		fi
	fi

exit $RET
