#!/bin/sh

if [ -n "$HALD_UNAME_S" -a -x ./$HALD_UNAME_S/hal-system-video-resume-$HALD_UNAME_S ]; then
    exec ./$HALD_UNAME_S/hal-system-video-resume-$HALD_UNAME_S $@
else
    echo "org.freedesktop.Hal.Device.UnknownError" >&2
    echo "No back-end for your operating system" >&2
    exit 1
fi
