#!/bin/sh

unsupported() {
	echo "org.freedesktop.Hal.Device.SystemPowerManagement.NotSupported" >&2
	echo "No reboot command found" >&2
	exit 1
}

POLICY=power-reboot
if [ "$HAL_METHOD_INVOKED_BY_UID" != "0" ] ; then
    polkit-is-privileged --policy $POLICY --uid $HAL_METHOD_INVOKED_BY_UID
    IS_PRIVILEGED=$?
    if [ "$IS_PRIVILEGED" != "0" ] ; then
	echo org.freedesktop.Hal.Device.PermissionDeniedByPolicy >&2
	echo $POLICY refused uid $HAL_METHOD_INVOKED_BY_UID >&2
	exit 1
    fi
fi

#Try for common tools
if [ -x "/sbin/shutdown" ] ; then
	/sbin/shutdown -r now
	exit $?
elif [ -x "/usr/sbin/shutdown" ] ; then
	/usr/sbin/shutdown -r now
	exit $?
else
	unsupported
fi
