#!/bin/sh

# Copyright (C) 2005, Kay Sievers <kay.sievers@vrfy.org>
# Copyright (C) 2006, David Zeuthen <david@fubar.dk>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2.
#
# Check for environment variables
if [ -z "$HAL_PROP_BLOCK_DEVICE" ] || [ -z "$HAL_PROP_INFO_UDI" ] ; then
    echo "org.freedesktop.Hal.Device.UnknownError" >&2
    echo "Missing or empty environment variable(s)." >&2
    echo "This script should be started by hald." >&2
    exit 1
fi

if [ "$HAL_METHOD_INVOKED_BY_UID" != "0" ]; then
    if [ -n "$HAL_PROP_INFO_HAL_MOUNT_CREATED_MOUNT_POINT" ]; then
	if [ "$HAL_METHOD_INVOKED_BY_UID" != "$HAL_PROP_INFO_HAL_MOUNT_MOUNTED_BY_UID" ]; then
	    echo "org.freedesktop.Hal.Device.Volume.PermissionDenied" >&2
	    echo "Volume mounted by uid $HAL_PROP_INFO_HAL_MOUNT_MOUNTED_BY_UID cannot be ejected by uid $HAL_METHOD_INVOKED_BY_UID." >&2
	    exit 1
	fi
    fi
fi

# TODO: need to select storage-[fixed|removable][-change-uid]
#POLICY=hal-storage-fixed-mount
#if [ "$HAL_METHOD_INVOKED_BY_UID" != "0" ] ; then
#    RESULT=$(polkit-is-privileged --privilege $POLICY --user $HAL_METHOD_INVOKED_BY_UID 2>&1)
#    IS_PRIVILEGED=$?
#    if [ "$IS_PRIVILEGED" != "0" ] ; then
#	echo org.freedesktop.Hal.Device.PermissionDeniedByPolicy >&2
#	echo $POLICY refused uid $HAL_METHOD_INVOKED_BY_UID >&2
#	exit 1
#    fi
#fi

if [ -n "$HALD_UNAME_S" -a -x $0-$HALD_UNAME_S ]; then
    exec $0-$HALD_UNAME_S $@
else
    echo "org.freedesktop.Hal.Device.UnknownError" >&2
    echo "No back-end for your operating system" >&2
    exit 1
fi
