#!/bin/sh

# Copyright (C) 2005, Kay Sievers <kay.sievers@vrfy.org>
# Copyright (C) 2006, David Zeuthen <davidz@redhat.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2.

if [ -n "$HALD_UNAME_S" -a -x ./$0-$HALD_UNAME_S ]; then
    exec ./$0-$HALD_UNAME_S $@
else
    echo "No back-end for your operating system" >&2
    exit 1
fi
